#!/bin/bash
[ -d /etc/nginx/shell.d ] && find /etc/nginx/shell.d -name '*.sh' -exec bash '{}' \;
[ -d /etc/nginx/pkg.d ] && find /etc/nginx/pkg.d -name '*.deb' -exec dpkg -i '{}' \;

echo "$@"
exec "$@"
